steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "${_REGISTRY}/${_IMAGE}:${SHORT_SHA}"
      - "-t"
      - "${_REGISTRY}/${_IMAGE}:latest"
      - "${_FOLDER}"

  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "${_REGISTRY}/${_IMAGE}:${SHORT_SHA}"

  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "${_REGISTRY}/${_IMAGE}:latest"

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "gcloud"
    args:
      - "run"
      - "deploy"
      - "${_SERVICE}"
      - "--image=${_REGISTRY}/${_IMAGE}:${SHORT_SHA}"
      - "--region=${_REGION}"
      - "--quiet"

substitutions:
  _REGION: europe-west1
  _REGISTRY: europe-west1-docker.pkg.dev/project3grupo1/app-repo

options:
  logging: CLOUD_LOGGING_ONLY